
service: kapochamo-invest
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  environment:
    TRADING_QUEUE_NAME: ${self:provider.stage}-trader-queue

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'
    - Effect: 'Allow'
      Action: ["sqs:GetQueueAttributes", "sqs:ReceiveMessage", "sqs:DeleteMessage", "sqs:SendMessage", "sqs:GetQueueUrl"]
      Resource:
        - !GetAtt TradingQueue.Arn
        - !GetAtt TradingQueueDLQ.Arn


custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm' # Packager that will be used to package your external modules
  warmup:
    enabled: true
    events:
      - schedule: rate(5 minutes)
    prewarm: true
    concurrency: 1
  prune:
    automatic: true
    number: 5 # Number of versions to keep


functions:
  testMe:
    handler: src/functions/testFunc.default
    description: Test lambda
    events:
      - http: GET hello
  watcherBinance:
    handler: src/functions/watcher.default
    description: Watch Binance news and trigger trader if needed
    events:
      - http: GET watcher
  trader:
    handler: src/functions/trader.default
    description: Buy and sell a symbol on Binance
    timeout: 900 # 15 minutes
    events:
      - sqs:
          arn: !GetAtt TradingQueue.Arn
          batchSize: 1

resources:
  Resources:
    EmailNotification:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Email Notification
        TopicName: EmailNotification
        Subscription:
          - Protocol: email
            Endpoint: rulliere.francois+kapochamo@gmail.com

    EventRule:
      Type: AWS::Events::Rule
      Properties:
        Description: "Send email on lambda notification"
        EventPattern:
          source:
            - "aws.lambda"
        State: "ENABLED"
        Targets:
          - Arn: !GetAtt TestMeLambdaFunction.Arn
            Id: "testLambda"

    # Queues
    TradingQueue:
      Type: AWS::SQS::Queue
      Properties:
        DelaySeconds: 0
        MessageRetentionPeriod: 345600 # 4 days
        QueueName: ${self:provider.environment.TRADING_QUEUE_NAME}
        ReceiveMessageWaitTimeSeconds: 0
        VisibilityTimeout: 900
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt TradingQueueDLQ.Arn
          maxReceiveCount: 1
      DependsOn:
        - TradingQueueDLQ
    TradingQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.TRADING_QUEUE_NAME}-DLQ
        MessageRetentionPeriod: 1209600 # 14 days



plugins:
  - serverless-webpack
  - serverless-plugin-warmup
  - serverless-prune-plugin
