CREATE TABLE news (
  id SERIAL NOT NULL PRIMARY KEY,
  title VARCHAR ,
  time TIMESTAMP ,
  content VARCHAR,
  url VARCHAR
);

CREATE TABLE symbol (
  symbol VARCHAR NOT NULL PRIMARY KEY,
  status VARCHAR NOT NULL,
  base_asset VARCHAR NOT NULL,
  quote_asset VARCHAR NOT NULL
);
