service: view-candle

provider:
  name: aws
  runtime: python3.8

functions:
  candle:
    handler: handler.main
    events:
      - http:
          path: candle/view
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
